### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Taronaga** [pslawinski/esphome_airconintl#2]
Hello.
Trying to replicate your experience of getting a compilation of cash.
log:

Processing garage-ac (board: esp01_1m; framework: arduino; platform: platformio/espressif8266@3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
Dependency Graph
|-- ESPAsyncTCP-esphome @ 1.2.3
|-- ESPAsyncWebServer-esphome @ 2.1.0
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- noise-c @ 0.1.4
Compiling /data/garage-ac/.pioenvs/garage-ac/src/main.cpp.o
Compiling /data/garage-ac/.pioenvs/garage-ac/libf4d/ESPAsyncWebServer-esphome/WebResponses.cpp.o
In file included from src/main.cpp:60:
src/aircon_climate.h: In constructor 'AirconClimate::AirconClimate(esphome::uart::UARTComponent*)':
src/aircon_climate.h:730:91: error: no matching function for call to 'esphome::sensor::Sensor::Sensor(const char [21])'
  730 |                                            indoor_humidity_status("Indoor Humidity status") {}
      |                                                                                           ^
In file included from src/esphome/core/controller.h:17,
                 from src/esphome/components/api/api_server.h:4,
                 from src/esphome/components/api/api_connection.h:6,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/components/sensor/sensor.h:59:12: note: candidate: 'esphome::sensor::Sensor::Sensor()'
   59 |   explicit Sensor();
      |            ^~~~~~
src/esphome/components/sensor/sensor.h:59:12: note:   candidate expects 0 arguments, 1 provided
src/esphome/components/sensor/sensor.h:57:7: note: candidate: 'esphome::sensor::Sensor::Sensor(const esphome::sensor::Sensor&)'
   57 | class Sensor : public EntityBase, public EntityBase_DeviceClass, public EntityBase_UnitOfMeasurement {
      |       ^~~~~~
src/esphome/components/sensor/sensor.h:57:7: note:   no known conversion for argument 1 from 'const char [21]' to 'const esphome::sensor::Sensor&'
src/esphome/components/sensor/sensor.h:57:7: note: candidate: 'esphome::sensor::Sensor::Sensor(esphome::sensor::Sensor&&)'
src/esphome/components/sensor/sensor.h:57:7: note:   no known conversion for argument 1 from 'const char [21]' to 'esphome::sensor::Sensor&&'
In file included from src/main.cpp:60:
src/aircon_climate.h:730:91: error: no matching function for call to 'esphome::sensor::Sensor::Sensor(const char [29])'
  730 |                                            indoor_humidity_status("Indoor Humidity status") {}
      |                                                                                           ^
In file included from src/esphome/core/controller.h:17,
                 from src/esphome/components/api/api_server.h:4,
                 from src/esphome/components/api/api_connection.h:6,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/components/sensor/sensor.h:59:12: note: candidate: 'esphome::sensor::Sensor::Sensor()'
   59 |   explicit Sensor();
      |            ^~~~~~
src/esphome/components/sensor/sensor.h:59:12: note:   candidate expects 0 arguments, 1 provided
src/esphome/components/sensor/sensor.h:57:7: note: candidate: 'esphome::sensor::Sensor::Sensor(const esphome::sensor::Sensor&)'
   57 | class Sensor : public EntityBase, public EntityBase_DeviceClass, public EntityBase_UnitOfMeasurement {
      |       ^~~~~~
src/esphome/components/sensor/sensor.h:57:7: note:   no known conversion for argument 1 from 'const char [29]' to 'const esphome::sensor::Sensor&'
src/esphome/components/sensor/sensor.h:57:7: note: candidate: 'esphome::sensor::Sensor::Sensor(esphome::sensor::Sensor&&)'
src/esphome/components/sensor/sensor.h:57:7: note:   no known conversion for argument 1 from 'const char [29]' to 'esphome::sensor::Sensor&&'
In file included from src/main.cpp:60:
src/aircon_climate.h:730:91: error: no matching function for call to 'esphome::sensor::Sensor::Sensor(const char [26])'
  730 |                                            indoor_humidity_status("Indoor Humidity status") {}
      |                                                                                           ^
In file included from src/esphome/core/controller.h:17,
                 from src/esphome/components/api/api_server.h:4,
                 from src/esphome/components/api/api_connection.h:6,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/components/sensor/sensor.h:59:12: note: candidate: 'esphome::sensor::Sensor::Sensor()'
   59 |   explicit Sensor();
      |            ^~~~~~
src/esphome/components/sensor/sensor.h:59:12: note:   candidate expects 0 arguments, 1 provided
src/esphome/components/sensor/sensor.h:57:7: note: candidate: 'esphome::sensor::Sensor::Sensor(const esphome::sensor::Sensor&)'
   57 | class Sensor : public EntityBase, public EntityBase_DeviceClass, public EntityBase_UnitOfMeasurement {
      |       ^~~~~~
src/esphome/components/sensor/sensor.h:57:7: note:   no known conversion for argument 1 from 'const char [26]' to 'const esphome::sensor::Sensor&'
src/esphome/components/sensor/sensor.h:57:7: note: candidate: 'esphome::sensor::Sensor::Sensor(esphome::sensor::Sensor&&)'
src/esphome/components/sensor/sensor.h:57:7: note:   no known conversion for argument 1 from 'const char [26]' to 'esphome::sensor::Sensor&&'
In file included from src/main.cpp:60:
src/aircon_climate.h:730:91: error: no matching function for call to 'esphome::sensor::Sensor::Sensor(const char [20])'
  730 |                                            indoor_humidity_status("Indoor Humidity status") {}
      |                                                                                           ^
In file included from src/esphome/core/controller.h:17,
                 from src/esphome/components/api/api_server.h:4,
                 from src/esphome/components/api/api_connection.h:6,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/components/sensor/sensor.h:59:12: note: candidate: 'esphome::sensor::Sensor::Sensor()'
   59 |   explicit Sensor();
      |            ^~~~~~
src/esphome/components/sensor/sensor.h:59:12: note:   candidate expects 0 arguments, 1 provided
src/esphome/components/sensor/sensor.h:57:7: note: candidate: 'esphome::sensor::Sensor::Sensor(const esphome::sensor::Sensor&)'
   57 | class Sensor : public EntityBase, public EntityBase_DeviceClass, public EntityBase_UnitOfMeasurement {
      |       ^~~~~~
src/esphome/components/sensor/sensor.h:57:7: note:   no known conversion for argument 1 from 'const char [20]' to 'const esphome::sensor::Sensor&'
src/esphome/components/sensor/sensor.h:57:7: note: candidate: 'esphome::sensor::Sensor::Sensor(esphome::sensor::Sensor&&)'
src/esphome/components/sensor/sensor.h:57:7: note:   no known conversion for argument 1 from 'const char [20]' to 'esphome::sensor::Sensor&&'
In file included from src/main.cpp:60:
src/aircon_climate.h:730:91: error: no matching function for call to 'esphome::sensor::Sensor::Sensor(const char [30])'
  730 |                                            indoor_humidity_status("Indoor Humidity status") {}
      |                                                                                           ^
In file included from src/esphome/core/controller.h:17,
                 from src/esphome/components/api/api_server.h:4,
                 from src/esphome/components/api/api_connection.h:6,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/components/sensor/sensor.h:59:12: note: candidate: 'esphome::sensor::Sensor::Sensor()'
   59 |   explicit Sensor();
      |            ^~~~~~
src/esphome/components/sensor/sensor.h:59:12: note:   candidate expects 0 arguments, 1 provided
src/esphome/components/sensor/sensor.h:57:7: note: candidate: 'esphome::sensor::Sensor::Sensor(const esphome::sensor::Sensor&)'
   57 | class Sensor : public EntityBase, public EntityBase_DeviceClass, public EntityBase_UnitOfMeasurement {
      |       ^~~~~~
src/esphome/components/sensor/sensor.h:57:7: note:   no known conversion for argument 1 from 'const char [30]' to 'const esphome::sensor::Sensor&'
src/esphome/components/sensor/sensor.h:57:7: note: candidate: 'esphome::sensor::Sensor::Sensor(esphome::sensor::Sensor&&)'
src/esphome/components/sensor/sensor.h:57:7: note:   no known conversion for argument 1 from 'const char [30]' to 'esphome::sensor::Sensor&&'
In file included from src/main.cpp:60:
src/aircon_climate.h:730:91: error: no matching function for call to 'esphome::sensor::Sensor::Sensor(const char [31])'
  730 |                                            indoor_humidity_status("Indoor Humidity status") {}
      |                                                                                           ^
In file included from src/esphome/core/controller.h:17,
                 from src/esphome/components/api/api_server.h:4,
                 from src/esphome/components/api/api_connection.h:6,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/components/sensor/sensor.h:59:12: note: candidate: 'esphome::sensor::Sensor::Sensor()'
   59 |   explicit Sensor();
      |            ^~~~~~
src/esphome/components/sensor/sensor.h:59:12: note:   candidate expects 0 arguments, 1 provided
src/esphome/components/sensor/sensor.h:57:7: note: candidate: 'esphome::sensor::Sensor::Sensor(const esphome::sensor::Sensor&)'
   57 | class Sensor : public EntityBase, public EntityBase_DeviceClass, public EntityBase_UnitOfMeasurement {
      |       ^~~~~~
src/esphome/components/sensor/sensor.h:57:7: note:   no known conversion for argument 1 from 'const char [31]' to 'const esphome::sensor::Sensor&'
src/esphome/components/sensor/sensor.h:57:7: note: candidate: 'esphome::sensor::Sensor::Sensor(esphome::sensor::Sensor&&)'
src/esphome/components/sensor/sensor.h:57:7: note:   no known conversion for argument 1 from 'const char [31]' to 'esphome::sensor::Sensor&&'
In file included from src/main.cpp:60:
src/aircon_climate.h:730:91: error: no matching function for call to 'esphome::sensor::Sensor::Sensor(const char [27])'
  730 |                                            indoor_humidity_status("Indoor Humidity status") {}
      |                                                                                           ^
In file included from src/esphome/core/controller.h:17,
                 from src/esphome/components/api/api_server.h:4,
                 from src/esphome/components/api/api_connection.h:6,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/components/sensor/sensor.h:59:12: note: candidate: 'esphome::sensor::Sensor::Sensor()'
   59 |   explicit Sensor();
      |            ^~~~~~
src/esphome/components/sensor/sensor.h:59:12: note:   candidate expects 0 arguments, 1 provided
src/esphome/components/sensor/sensor.h:57:7: note: candidate: 'esphome::sensor::Sensor::Sensor(const esphome::sensor::Sensor&)'
   57 | class Sensor : public EntityBase, public EntityBase_DeviceClass, public EntityBase_UnitOfMeasurement {
      |       ^~~~~~
src/esphome/components/sensor/sensor.h:57:7: note:   no known conversion for argument 1 from 'const char [27]' to 'const esphome::sensor::Sensor&'
src/esphome/components/sensor/sensor.h:57:7: note: candidate: 'esphome::sensor::Sensor::Sensor(esphome::sensor::Sensor&&)'
src/esphome/components/sensor/sensor.h:57:7: note:   no known conversion for argument 1 from 'const char [27]' to 'esphome::sensor::Sensor&&'
In file included from src/main.cpp:60:
src/aircon_climate.h:730:91: error: no matching function for call to 'esphome::sensor::Sensor::Sensor(const char [36])'
  730 |                                            indoor_humidity_status("Indoor Humidity status") {}
      |                                                                                           ^
In file included from src/esphome/core/controller.h:17,
                 from src/esphome/components/api/api_server.h:4,
                 from src/esphome/components/api/api_connection.h:6,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/components/sensor/sensor.h:59:12: note: candidate: 'esphome::sensor::Sensor::Sensor()'
   59 |   explicit Sensor();
      |            ^~~~~~
src/esphome/components/sensor/sensor.h:59:12: note:   candidate expects 0 arguments, 1 provided
src/esphome/components/sensor/sensor.h:57:7: note: candidate: 'esphome::sensor::Sensor::Sensor(const esphome::sensor::Sensor&)'
   57 | class Sensor : public EntityBase, public EntityBase_DeviceClass, public EntityBase_UnitOfMeasurement {
      |       ^~~~~~
src/esphome/components/sensor/sensor.h:57:7: note:   no known conversion for argument 1 from 'const char [36]' to 'const esphome::sensor::Sensor&'
src/esphome/components/sensor/sensor.h:57:7: note: candidate: 'esphome::sensor::Sensor::Sensor(esphome::sensor::Sensor&&)'
src/esphome/components/sensor/sensor.h:57:7: note:   no known conversion for argument 1 from 'const char [36]' to 'esphome::sensor::Sensor&&'
In file included from src/main.cpp:60:
src/aircon_climate.h:730:91: error: no matching function for call to 'esphome::sensor::Sensor::Sensor(const char [24])'
  730 |                                            indoor_humidity_status("Indoor Humidity status") {}
      |                                                                                           ^
In file included from src/esphome/core/controller.h:17,
                 from src/esphome/components/api/api_server.h:4,
                 from src/esphome/components/api/api_connection.h:6,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/components/sensor/sensor.h:59:12: note: candidate: 'esphome::sensor::Sensor::Sensor()'
   59 |   explicit Sensor();
      |            ^~~~~~
src/esphome/components/sensor/sensor.h:59:12: note:   candidate expects 0 arguments, 1 provided
src/esphome/components/sensor/sensor.h:57:7: note: candidate: 'esphome::sensor::Sensor::Sensor(const esphome::sensor::Sensor&)'
   57 | class Sensor : public EntityBase, public EntityBase_DeviceClass, public EntityBase_UnitOfMeasurement {
      |       ^~~~~~
src/esphome/components/sensor/sensor.h:57:7: note:   no known conversion for argument 1 from 'const char [24]' to 'const esphome::sensor::Sensor&'
src/esphome/components/sensor/sensor.h:57:7: note: candidate: 'esphome::sensor::Sensor::Sensor(esphome::sensor::Sensor&&)'
src/esphome/components/sensor/sensor.h:57:7: note:   no known conversion for argument 1 from 'const char [24]' to 'esphome::sensor::Sensor&&'
In file included from src/main.cpp:60:
src/aircon_climate.h:730:91: error: no matching function for call to 'esphome::sensor::Sensor::Sensor(const char [23])'
  730 |                                            indoor_humidity_status("Indoor Humidity status") {}
      |                                                                                           ^
In file included from src/esphome/core/controller.h:17,
                 from src/esphome/components/api/api_server.h:4,
                 from src/esphome/components/api/api_connection.h:6,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/components/sensor/sensor.h:59:12: note: candidate: 'esphome::sensor::Sensor::Sensor()'
   59 |   explicit Sensor();
      |            ^~~~~~
src/esphome/components/sensor/sensor.h:59:12: note:   candidate expects 0 arguments, 1 provided
src/esphome/components/sensor/sensor.h:57:7: note: candidate: 'esphome::sensor::Sensor::Sensor(const esphome::sensor::Sensor&)'
   57 | class Sensor : public EntityBase, public EntityBase_DeviceClass, public EntityBase_UnitOfMeasurement {
      |       ^~~~~~
src/esphome/components/sensor/sensor.h:57:7: note:   no known conversion for argument 1 from 'const char [23]' to 'const esphome::sensor::Sensor&'
src/esphome/components/sensor/sensor.h:57:7: note: candidate: 'esphome::sensor::Sensor::Sensor(esphome::sensor::Sensor&&)'
src/esphome/components/sensor/sensor.h:57:7: note:   no known conversion for argument 1 from 'const char [23]' to 'esphome::sensor::Sensor&&'
Compiling /data/garage-ac/.pioenvs/garage-ac/libf4d/ESPAsyncWebServer-esphome/WebServer.cpp.o
*** [/data/garage-ac/.pioenvs/garage-ac/src/main.cpp.o] Error 1
========================= [FAILED] Took 21.68 seconds =========================

**Comment by pslawinski** [comment]
Should be fixed now.
